### PR TITLE
test: add Lagon tests

### PR DESCRIPTION
**Pull request by QuiiBz**
This PR adds Lagon to the test suite. I'll mark this PR as ready when all the issues are fixed.

Currently failing tests:
- `doesn't fully buffer binary stream` outputs less than 10 (fixed by https://github.com/lagonapp/lagon/pull/460)
- `set-cookie` headers aren't splitter (fixed by https://github.com/lagonapp/lagon/pull/622)
- `session` counter stays at 1 instead of incrementing (fixed by https://github.com/lagonapp/lagon/pull/608)

### CODE REVIEW

**Comment by QuiiBz** [comment]
> This PR adds Lagon to the test suite. I'll mark this PR as ready when all the issues are fixed.
> 
> Currently failing tests:
> 
> * `doesn't fully buffer binary stream` outputs less than 10
> * `set-cookie` headers aren't splitted
> * `session` counter stays at 1 instead of incrementing

**Comment by QuiiBz** [comment]
Waiting for https://github.com/lagonapp/lagon/pull/622 to be released to undraft this PR

**Comment by cyco130** [comment]
Is Lagon supposed to work on Windows? I can't find any mention of it. If not, we can just disable the Windows CI for the Lagon case and merge this maybe?

**Comment by QuiiBz** [comment]
> Is Lagon supposed to work on Windows? I can't find any mention of it. If not, we can just disable the Windows CI for the Lagon case and merge this maybe?

It should work, but because `esbuild` isn't installed globally, the CI fails because the path to esbuild isn't found. I'm gonna update the CI to install esbuild globally, which should fix the issue!

**Comment by QuiiBz** [comment]
I pushed a fix that *should* makes the CI green 🤞

**Comment by cyco130** [comment]
Other failing tests are due to a bug in Node 18.14.1 related to cookie handling (fixed in .2 but the GitHub action didn't update yet). But it still can't seem to find ESBuild.

**Comment by QuiiBz** [comment]
I've created https://github.com/lagonapp/lagon/issues/629 to resolve the issue with ESBuild on Windows. This would remove completely the need to install ESBuild globally.

**Comment by cyco130** [comment]
Can't react on the phone but 👍

**Comment by QuiiBz** [comment]
Released https://github.com/lagonapp/lagon/pull/636 that should fix the path issue with Windows!

**Comment by cyco130** [comment]
:victory-dance:

**Pull request merged**
