### PR TITLE
add: test client [WIP]

### PR DESCRIPTION
**Pull request by tkamenoko**
**This PR is incomplete! Feel free to rewrite/advise to improve API.**

Add test client feature described in #36 .

It enables to test request handlers without running a real server.

See `readme.md` to find TODOs.

### CODE REVIEW

**Comment by cyco130** [comment]
I think this is a pretty good idea. Looks good to me so far, I'll have a deeper look when I have more time.

**Comment by cyco130** [comment]
I kind of need this now so I'm planning to merge it :)

I know some functionality is missing but we can add it later, when needed.

**Comment by tkamenoko** [comment]
@cyco130 Thank you for merging! I created PR #46 to attache a license to the package. Please review that.

**Comment by cyco130** [comment]
Merged. Thank you, it's been a valuable addition, already used in almost all tests :)

**Pull request merged**
