### PR TITLE
Retrieve client IP for Bun adapter

### PR DESCRIPTION
**Pull request by h-takeyeah**
Thanks for hattip!

In this PR, I answered:
https://github.com/hattipjs/hattip/blob/b8697cb360c16609eff560cff7993da114b5022c/packages/adapter/adapter-bun/src/index.ts#L52

The way to retrieve client IP on the server side was implemented at https://github.com/oven-sh/bun/pull/6165, which I followed.

**I don't know how to write test code, and this is my first contribution to hattip, so please take careful review.** :pray:

By the way, I can't find why this package `adapter-bun` contains(contained) `src/bun-types.ts` while it already has a dependency of `bun-types` (but not used). Though there would be historical background, replacing the self-contained type definition with `@types/bun` which just references `bun-types` is no problem. That's why I decided to update the dependencies. If you have any specific reasons for avoiding the use of `@types/bun`, please inform me. :smile:

When I removed the package by running `pnpm rm bun-types`, `pnpm-lock.yaml` was updated to not only delete the `bun-types` entry but also add the `debug` package. Did I make a mistake?

### CODE REVIEW

**Comment by cyco130** [comment]
Thanks, looks great!

Just two things:

1. I updated the deps just a few minutes ago, can you rebase on top of that?
2. Looks like we should put the `server` argument into the platform object, you wanna do that as well?

**Comment by h-takeyeah** [comment]
Thanks all for the lighting fast response!

1. OK, I will wait your work,
2. I never tried that though it's probably OK. Please wail till figure out term of _platform_...

**Comment by h-takeyeah** [comment]
I will try to create new bun project using hattip.

**Comment by cyco130** [comment]
Sorry if I wasn't clear. I meant the line that has `platform: { name: "bun", server: this }`. I thought passing `server` there instead of `this` would be more readable/explicit.

**Comment by h-takeyeah** [comment]
OK. Thanks for your explanation. It became clear! Yes, putting `server` there instead of `this` is better.

It's a small detail though which is better?
```js
// A
platform: { name: "bun", server: server },
// B
platform: { name: "bun", server },
```
ESLint did not complained to both of them.

**Comment by cyco130** [comment]
I'm not picky at all but B is shorter :)

**Comment by h-takeyeah** [comment]
@cyco130

By looking around, this PR may break TypeScript types :sweat:

**What happened**

But looking publish-ready `package.json` (\*), `bun-types` is not in the `dependencies` dictionary, and when I created new bun project and add dependency `bun add @hattip/adapter-bun`, it was not added automatically.

(\*) build by `pnpm build && pnpm pack`

```jsonc
// current
  "dependencies": {
    "bun-types": "^1.0.26",
    "@hattip/core": "0.0.42"
  },

// this PR
  "dependencies": {
    "@types/bun": "^1.0.5",
    "@hattip/core": "0.0.42"
  },
```

Here is details:

<details>
<summary>differences between current package.json and newer one</summary>
current:
```json
{
  "name": "@hattip/adapter-bun",
  "version": "0.0.42",
  "type": "module",
  "description": "Bun adapter for Hattip",
  "files": [
    "dist"
  ],
  "exports": "./dist/index.js",
  "typesVersions": {
    "*": {
      "*": [
        "dist/*.d.ts"
      ]
    }
  },
  "author": "Fatih Aygün <cyco130@gmail.com>",
  "repository": "https://github.com/hattipjs/hattip",
  "license": "MIT",
  "dependencies": {
    "bun-types": "^1.0.26",
    "@hattip/core": "0.0.42"
  },
  "devDependencies": {
    "@cyco130/eslint-config": "^3.6.3",
    "@types/node": "^20.11.16",
    "eslint": "^8.56.0",
    "publint": "^0.2.7",
    "tsup": "^8.0.1",
    "typescript": "^5.3.3"
  },
  "scripts": {
    "build": "rimraf dist && tsup",
    "dev": "tsup --watch",
    "test": "pnpm test:typecheck && pnpm test:lint && pnpm test:package",
    "test:typecheck": "tsc -p tsconfig.json --noEmit",
    "test:lint": "eslint . --max-warnings 0 --ignore-pattern dist",
    "test:package": "publint --strict"
  }
}
```

this PR:
```json
{
  "name": "@hattip/adapter-bun",
  "version": "0.0.42",
  "type": "module",
  "description": "Bun adapter for Hattip",
  "files": [
    "dist"
  ],
  "exports": "./dist/index.js",
  "typesVersions": {
    "*": {
      "*": [
        "dist/*.d.ts"
      ]
    }
  },
  "author": "Fatih Aygün <cyco130@gmail.com>",
  "repository": "https://github.com/hattipjs/hattip",
  "license": "MIT",
  "dependencies": {
    "@types/bun": "^1.0.5",
    "@hattip/core": "0.0.42"
  },
  "devDependencies": {
    "@cyco130/eslint-config": "^3.6.3",
    "@types/node": "^20.11.16",
    "eslint": "^8.56.0",
    "publint": "^0.2.7",
    "tsup": "^8.0.1",
    "typescript": "^5.3.3"
  },
  "scripts": {
    "build": "rimraf dist && tsup",
    "dev": "tsup --watch",
    "test": "pnpm test:typecheck && pnpm test:lint && pnpm test:package",
    "test:typecheck": "tsc -p tsconfig.json --noEmit",
    "test:lint": "eslint . --max-warnings 0 --ignore-pattern dist",
    "test:package": "publint --strict"
  }
}
```

</details>

I thought `bun-types` is automatically installed when users add `@hattip/adapter-bun` as a their projects' dependency since `@hattip/adapter-bun` transitively depends on it via `@types/bun`. And so explicit marking as `dependencies: { "bun-types": "..." }` is not needed but my understanding might be incorrect.

**Solutions**

I think there is 2 options.
1. Add both of them as dependency.
2. Continue using `bun-types` but adding `"compilerOptions": { "types": ["bun-types"]}` to `packages/adapters/adapter-bun/tsconfig.json`

What do you think about this?

---

How to solve the conflicting on `pnpm-lock.yaml` ?

`@typescript-eslint/*` packages somehow downgrade. If you couldn't reproduce, it's my environment specific issue sorry.

To reproduce:
1. head to current(Fri, 16 Feb 2024 17:36:02 GMT) main branch https://github.com/hattipjs/hattip/commit/b8697cb360c16609eff560cff7993da114b5022c
2. cd `packages/adapters/adapter-bun`
4. run `pnpm rm bun-types && pnpm add @types/bun`
5. see `pnpm-lock.yaml`

**Comment by h-takeyeah** [comment]
https://github.com/hattipjs/hattip/pull/129#issuecomment-1949015193

**correct** `bun-types` is installed when I add `@hattip/adapter-bun`. I misunderstood. I'm sorry. Though, `pnpm-lock.yaml` still conflicts, and other problems occur:

image

This is example code to use `bunAdapter()`. Since `BunAdapterOptions` is intersection type of (Omit) `Serve` and `staticDir: ..., trustProxy...`, and type `Serve` derives from `bun` module, the property `hostname` should be inferred as the property of `ServeOptions` but actually not.

```ts
// index.d.ts of adapter-bun
import { Serve, Server } from 'bun';

type BunAdapterOptions = Omit<Serve, "fetch" | "error"> & {
    staticDir?: string;
    trustProxy?: boolean;
};
```

I can't figure out why, I want someone's help. Or should I rollback?

note: As JavaScript, this PR worked fine.

**Comment by h-takeyeah** [comment]
I noticed `npm run test` failed. I apologize for creating this pull request without making sure the test passed.

It seems that [`server.requestIP(req)`](https://github.com/oven-sh/bun/blob/c34bbb2e3fcaaadd8dfb5e75d545acee1c3cfd1b/packages/bun-types/bun.d.ts#L2628) returns the address in a style we don't expect when no hostname is set.

:no_good: without hostname
```
$ curl http://localhost:3000                                                                                      
{
  address: "::ffff:127.0.0.1",
  family: "IPv6",
  port: 52620,
}
```

:ok_person: with hostname
```
$ curl http://localhost:3000
{
  address: "127.0.0.1",
  family: "IPv4",
  port: 49402,
}
```

`bun run server.ts`
```ts
// server.ts
import type { ServeOptions } from "bun";

export default {
    //hostname: "127.0.0.1",
    fetch(request, server) {
        return new Response(Bun.inspect(server.requestIP(request)))
    },
} satisfies ServeOptions
```

**Comment by h-takeyeah** [comment]
Attach test log [^tips]
[20240217-1714-pnpm-run-ci.log](https://github.com/hattipjs/hattip/files/14318172/20240217-1714-pnpm-run-ci.log)

> ```
> AssertionError: expected [ '<h1>Hello from Hattip!</h1><p>URL: <span>http://127.0.0.1:3000/</span></p><p>Your IP address is: <span>127.0.0.1</span></p>', '<h1>Hello from Hattip!</h1><p>URL: <span>http://127.0.0.1:3000/</span></p><p>Your IP address is: <span>::1</span></p>' ] to include '<h1>Hello from Hattip!</h1><p>URL: <span>http://127.0.0.1:3000/</span></p><p>Your IP address is: <span>::ffff:127.0.0.1</span></p>'
>```

[^tips]: By default, every long AssertionError is truncated. To prevent this I followed this instruction: [chaiConfig.truncateThreshold](https://vitest.dev/config/#chaiconfig-truncatethreshold)

**Comment by cyco130** [comment]
No need to apologize! The CI is the place to run tests you don't _have_ to run them locally.

It's the tests that are in the wrong in this case, `::ffff:127.0.0.1` is an acceptable IP address to return in this case. I just pushed a fix.

**Comment by h-takeyeah** [comment]
Thanks for many help! What is remaining?

**Comment by cyco130** [comment]
CI is green. merging 🎊 

Thank you for your efforts!

I'll publish a new release later today (most likely).

**Comment by cyco130** [comment]
Published in 0.0.43.

**Pull request merged**
