### PR TITLE
fix: cookies of request for aws lambda payload format v2

### PR DESCRIPTION
**Pull request by princescar**
Put cookies back to headers to construct a complete request for hattip handler.

### CODE REVIEW

**Comment by cyco130** [comment]
Hi!

I don't understand the necessity of this. `event.cookie` seems to be purely for convenience, `event.headers` already seems to contain the `cookie` header as you can check below. It's a non-streaming AWS deployment of [this test file](https://github.com/hattipjs/hattip/blob/main/testbed/basic/index.js). I also tested streaming version, works the same):

- https://nerdt5onfqrnufze6v76j6qmc40ihmgq.lambda-url.eu-west-3.on.aws/set-cookie (sets two cookies)
- https://nerdt5onfqrnufze6v76j6qmc40ihmgq.lambda-url.eu-west-3.on.aws/headers (dumps the request headers, should show the `cookie` header)
- https://nerdt5onfqrnufze6v76j6qmc40ihmgq.lambda-url.eu-west-3.on.aws/cookie (dumps parsed cookies)

Maybe there's a configuration setting that I'm not aware that requires your patch?

**Comment by princescar** [comment]
Hi @cyco130, I should mention that this is for the v2 payload format.

For the v2 payload, API gateway removes the `Cookies` header from event, and the hattip handler cannot get construct the full request with cookies.

References:
- https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
- https://github.com/awslabs/aws-lambda-go-api-proxy/pull/109/files

**Comment by cyco130** [comment]
Hattip's also using v2. But if it's the _API gateway_ that removes it, I wouldn't know because I don't use it (I just create a function URL and put it behind a CF worker, I'm cheap 😃).

How about only overwriting `event.headers.cookie` if it's empty (e.g. guard it with `if (!event.headers.cookie)` or something)? I'll merge if you can make a change to that effect.

Thanks for reporting!

**Comment by princescar** [comment]
Hey @cyco130, it's updated!

**Comment by cyco130** [comment]
Thank you for your contribution!

**Pull request merged**
